SELECT
    B.TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
-- WHERE MONTH(B.CREATED_DATE) = 10
-- WHERE B.CREATED_DATE like '2022-10%'
-- WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
-- WHERE SUBSTR(B.CREATED_DATE,1,7) = '2022-10'
WHERE B.CREATED_DATE BETWEEN ('2022-10-01') AND ('2022-10-31')
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;